### ISSUE TITLE
Create the styleA.css

### ISSUE THREAD

**Issue by Djis247** [Djis247/p1#5]
If the HTML file links to styleA.css then it should appear like this ("Version A"):
![image](https://github.com/Djis247/p1/assets/37152540/8f56dfcb-eabc-4968-a963-7bf1c9919a8b)

### Style A Specifications

- There should be six box elements, lined up vertically.
- All boxes are centered horizontally and equally spaced vertically. When the browser window is resized, the spacing between the boxes should change (they should be equally spaced vertically across the page). However, the boxes themselves should never overlap or change size.
- Each box is 100x100 pixels, with a 1px line (color: #687291) on top. Text is centered horizontally.
- Boxes alternate colors (colors: #dfe1e7, #eeeff2).
- The final element (color: #687291) has a 4px, black border and the text is centered vertically.
- The font in all elements is Tahoma, 40 pixels.

**Comment by dsprad99** [comment]
Style A has been completed.
