### ISSUE TITLE
Create the styleB.css

### ISSUE THREAD

**Issue by Djis247** [Djis247/p1#6]
If the HTML file links to styleB.css then it should appear like this ("Version B"):

Note: The D in the screenshot is highlighted to show you what space the text should occupy. Your solution should not style the D with a blue background.

![image](https://github.com/Djis247/p1/assets/37152540/8f456bd6-94a3-4480-b285-4c15bba95198)

### Style B Specifications

- Five box elements, lined up horizontally in the top left corner.
- Boxes do not wrap with window resizing (i.e. Boxes A through E should stay on the same line even if your browser window is too small to display them all).
- The last box is positioned in the bottom right corner of the window and stays there even when the window resizes.
- Each box is 100x150 pixels (color: #eeeff2), with a 10px dotted line (color: #D0D0FF) on the left. Boxes are separated by 10 pixels of space.
- When hovering over a box, the cursor changes to a hand and the box and font colors change (colors: yellow, goldenrod, respectively).
- The font in all elements is Tahoma, 40 pixels.
- There are 10 pixels of space between the letters and the edge of the box.

If a property is not outlined in these specifications (e.g. space between elements in style B and edge of window) you should choose something reasonable.

**Comment by BareRen** [comment]
Style B has been completed.
